# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js base image
FROM node:18-alpine AS builder

# Create a directory for the app
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the project
RUN npm run build

# Use the same Node.js base image for the final container
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the build output and necessary files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the environment variables for the Conda environment
ENV CODE_STORAGE_DIR=/path/to/code/storage
ENV CONDA_ENV_NAME=your-conda-env

# Specify the command to run the MCP Code Executor server
ENTRYPOINT ["node", "build/index.js"]
